on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

name: Build and Release

jobs:
  build-and-release:
    name: Build AIX and Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build AIX
        id: build
        uses: pavi2410/AIX-Action@main
        with:
          package-name: me.pavi2410
        
      - name: Check build output
        run: |
          ls -la $(dirname ${{ steps.build.outputs.extension-path }})
          file ${{ steps.build.outputs.extension-path }}
        
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.build.outputs.extension-path }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
